version: "3"
services:
  nodejs:
    tty: true
    image: "docker.io/bitnami/node:${NODEJS_VERSION}-debian-10"
    ports:
      - "${NODEJS_HTTP_PORT}:3000"
    volumes:
      - "${APP_CODE_PATH_HOST}:/app"
volumes: {}
