version: '3'
services:
  nodejs:
    build:
      context: '.'
      args:
      - 'NODEJS_VERSION=${NODEJS_VERSION}'
    volumes:
      - ${APP_CODE_PATH_HOST}:/src
    command: npm run start
    ports:
      - "${NODEJS_HTTP_PORT}:3000"
volumes: {}
