version: '3'
services:
  nodejs:
    build:
      context: '.'
      args:
      - 'NODEJS_VERSION=${NODEJS_VERSION}'
      target: dev
    volumes:
      - ${APP_CODE_PATH_HOST}:/src
    environment:
      - NODE_ENV=development
      - DEBUG=nodejs-docker-express:*
    command: npm run start
    ports:
      - "${NODEJS_HTTP_PORT}:3000"
volumes: {}
