name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image Nodejs 10
      run: docker-compose build
      env:
        NODEJS_VERSION: 10
    
    - name: Build the Docker image Nodejs 12
      run: docker-compose build
      env:
        NODEJS_VERSION: 12

    - name: Build the Docker image Nodejs 13
      run: docker-compose build
      env:
        NODEJS_VERSION: 13
    
    - name: Build the Docker image Nodejs 14
      run: docker-compose build
      env:
        NODEJS_VERSION: 14
    
    - name: Build the Docker image Nodejs 16
      run: docker-compose build
      env:
        NODEJS_VERSION: 16


    - name: Build the Docker image Nodejs 16
      run: docker-compose build
      env:
        NODEJS_VERSION: 17


    - name: Build the Docker image Nodejs 16
      run: docker-compose build
      env:
        NODEJS_VERSION: 18